apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  namespace: elk
spec:
  selector:
    matchLabels:
      {{- include "adservice.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "adservice.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
      - name: server
        image: {{ .Values.adservice.image }}
        ports:
        - containerPort: 9555
        env:
        - name: PORT
          value: "9555"
        resources:
        {{- toYaml .Values.adservice.resources | nindent 10 }}
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:9555"]
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:9555"]

---

apiVersion: v1
kind: Service
metadata:
  name: adservice
  namespace: elk
spec:
  type: ClusterIP
  selector:
    {{- include "adservice.labels" . | nindent 4 }}
  ports:
  - name: grpc
    port: 9555
    targetPort: 9555