apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  namespace: elk
spec:
  selector:
    matchLabels:
      {{- include "checkoutservice.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "checkoutservice.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: server
          image: {{ .Values.checkoutservice.image }}
          ports:
          - containerPort: 5050
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:5050"]
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:5050"]
          env:
          - name: PORT
            value: "5050"
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "productcatalogservice:3550"
          - name: SHIPPING_SERVICE_ADDR
            value: "shippingservice:50051"
          - name: PAYMENT_SERVICE_ADDR
            value: "paymentservice:50051"
          - name: EMAIL_SERVICE_ADDR
            value: "emailservice:5000"
          - name: CURRENCY_SERVICE_ADDR
            value: "currencyservice:7000"
          - name: CART_SERVICE_ADDR
            value: "cartservice:7070"
          # - name: DISABLE_STATS
          #   value: "1"
          # - name: DISABLE_TRACING
          #   value: "1"
          # - name: DISABLE_PROFILER
          #   value: "1"
          # - name: JAEGER_SERVICE_ADDR
          #   value: "jaeger-collector:14268"
          resources:
            {{- toYaml .Values.checkoutservice.resources | nindent 12 }}

---

apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
  namespace: elk
spec:
  type: ClusterIP
  selector:
    {{- include "checkoutservice.labels" . | nindent 4 }}
  ports:
  - name: grpc
    port: 5050
    targetPort: 5050