apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  namespace: elk
spec:
  selector:
    matchLabels:
      {{- include "emailservice.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "emailservice.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
      - name: server
        image: {{ .Values.emailservice.image }}
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        # - name: DISABLE_TRACING
        #   value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        readinessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        livenessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        resources:
          {{- toYaml .Values.emailservice.resources | nindent 10 }}

---

apiVersion: v1
kind: Service
metadata:
  name: emailservice
  namespace: elk
spec:
  type: ClusterIP
  selector:
    {{- include "emailservice.labels" . | nindent 4 }}
  ports:
  - name: grpc
    port: 5000
    targetPort: 5000