apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
  namespace: elk
spec:
  selector:
    matchLabels:
      {{- include "productcatalogservice.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "productcatalogservice.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
      - name: server
        image: {{ .Values.productcatalogservice.image }}
        ports:
        - containerPort: 3550
        env:
        - name: PORT
          value: "3550"
        # - name: DISABLE_STATS
        #   value: "1"
        # - name: DISABLE_TRACING
        #   value: "1"
        # - name: DISABLE_PROFILER
        #   value: "1"
        # - name: JAEGER_SERVICE_ADDR
        #   value: "jaeger-collector:14268"
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:3550"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:3550"]
        resources:
          {{- toYaml .Values.paymentservice.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  namespace: elk
spec:
  type: ClusterIP
  selector:
    {{- include "productcatalogservice.labels" . | nindent 4 }}
  ports:
  - name: grpc
    port: 3550
    targetPort: 3550