apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
  namespace: elk
spec:
  selector:
    matchLabels:
      {{- include "recommendationservice.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "recommendationservice.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
      - name: server
        image: {{ .Values.recommendationservice.image }}
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        # livenessProbe:
        #   periodSeconds: 5
        #   exec:
        #     command: ["/bin/grpc_health_probe", "-addr=:8080"]
        env:
        - name: PORT
          value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice:3550"
        resources:
          {{- toYaml .Values.paymentservice.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
  namespace: elk
spec:
  type: ClusterIP
  selector:
    {{- include "recommendationservice.labels" . | nindent 4 }}
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080