apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
  namespace: elk
spec:
  selector:
    matchLabels:
      {{- include "shippingservice.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "shippingservice.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
      - name: server
        image: {{ .Values.shippingservice.image }}
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        readinessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        resources:
          {{- toYaml .Values.shippingservice.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
  namespace: elk
spec:
  type: ClusterIP
  selector:
    {{- include "shippingservice.labels" . | nindent 4 }}
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051